### ISSUE TITLE
Created ticket says Server: NULL

### ISSUE THREAD

**Issue by TNTUP** [AddstarMC/SimpleHelpTickets#11]
Hey, you may remember me, still using your plugin on my servers and now working with mysql and behind bungeecord proxy. Slight thing I noticed, when I create a ticket, it says "Server: Unknown". I hope it won't force/require me to use BungeeChat as I already uses DeluxeChat and I refuse to replace/redoing configs if necessary.

I'm thinking a way, adding a line in the config.yml, "ServerName: insertservername" then the tickets will know where the ticket is created. Now I want to know with this setting on, think if its possible to teleport the staff where the player created a ticket in a world in a certain server? 

The plugin would detect I'm running behind a bungeecord proxy so it would know how to send the staff to the ticket.

PS: Sorry if you can't understand it properly, English isn't my native tongue. Don't know either if you're open to issues or suggestions, as this plugin is mainly made for your server, not for others. 

Let me know if its possible or not, I'll close the ticket and ignoring the "Unknown" in tickets^^

**Comment by Narimm** [comment]
add a "server-id" to your config with the servername

it must be the same as whatever teleport plugin your server network uses

**Comment by TNTUP** [comment]
Thanks! Best support here x)
